// File: lib/features/profile/providers/profile_provider.dart
// Purpose: Riverpod mock profile providers for UG, PG, and PhD student personas.

import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../models/student_profile.dart';

final selectedProfileIndexProvider = StateProvider<int>((ref) => 0);

final studentProfileProvider = Provider<StudentProfile>((ref) {
  final index = ref.watch(selectedProfileIndexProvider);
  return _mockProfiles[index.clamp(0, _mockProfiles.length - 1)];
});

final _mockProfiles = <StudentProfile>[
  StudentProfile(
    studentId: '24K-518133',
    fullName: 'Muhammad Taha',
    department: 'Computer Science',
    faculty: 'Faculty of Computing',
    program: 'BS Computer Science',
    programType: ProgramType.undergraduate,
    currentSemester: 4,
    totalSemesters: 8,
    enrollmentStatus: EnrollmentStatus.active,
    academicStanding: AcademicStanding.deanslist,
    cgpa: 3.71,
    semesterGpa: 3.84,
    creditHoursCompleted: 54,
    creditHoursRequired: 136,
    currentCourses: const [
      SemesterCourse(
        code: 'CS301',
        name: 'Data Structures',
        creditHours: 3,
        grade: 'A',
        gradePoints: 4.0,
      ),
      SemesterCourse(
        code: 'CS305',
        name: 'Database Systems',
        creditHours: 3,
        grade: 'A-',
        gradePoints: 3.7,
      ),
      SemesterCourse(
        code: 'MG101',
        name: 'Expository Writing',
        creditHours: 2,
        grade: 'B+',
        gradePoints: 3.3,
      ),
    ],
    gpaHistory: const [3.45, 3.58, 3.64, 3.84],
    attendance: const [
      CourseAttendance(
        courseCode: 'CS301',
        courseName: 'Data Structures',
        attended: 24,
        total: 28,
      ),
      CourseAttendance(
        courseCode: 'CS305',
        courseName: 'Database Systems',
        attended: 22,
        total: 28,
      ),
      CourseAttendance(
        courseCode: 'MG101',
        courseName: 'Expository Writing',
        attended: 18,
        total: 24,
      ),
    ],
    dateOfBirth: '2007-02-07',
    gender: 'Male',
    bloodGroup: 'AB+',
    cnic: '32402-1272329-1',
    personalEmail: 'muhammad.taha.dandhla@gmail.com',
    universityEmail: 'taha.bscs24.nbc@nust..edu.pk',
    phone: '+92 335 64 60508',
    emergencyContact: '+92 335 6460508',
    address: 'Block 7, Gulshan-e-Iqbal, Karachi',
    major: 'Artificial Intelligence',
    minor: 'Software Engineering',
    internshipStatus: 'Summer Internship Confirmed - Systems Ltd',
    research: null,
    feeStatus: FeeStatus.partial,
    outstandingDues: 0,
    scholarshipName: 'Merit Scholarship',
    scholarshipDiscount: 100,
    profileImagePath: null,
  ),
  StudentProfile(
    studentId: 'MS23-1112',
    fullName: 'Usman Farooq',
    department: 'Software Engineering',
    faculty: 'Faculty of Computing',
    program: 'MS Software Engineering',
    programType: ProgramType.postgraduate,
    currentSemester: 2,
    totalSemesters: 4,
    enrollmentStatus: EnrollmentStatus.active,
    academicStanding: AcademicStanding.goodStanding,
    cgpa: 3.52,
    semesterGpa: 3.43,
    creditHoursCompleted: 18,
    creditHoursRequired: 30,
    currentCourses: const [
      SemesterCourse(
        code: 'SE621',
        name: 'Advanced Software Architecture',
        creditHours: 3,
        grade: 'B+',
        gradePoints: 3.3,
      ),
      SemesterCourse(
        code: 'SE631',
        name: 'Software Quality Assurance',
        creditHours: 3,
        grade: 'A-',
        gradePoints: 3.7,
      ),
      SemesterCourse(
        code: 'SE699',
        name: 'Thesis-I',
        creditHours: 6,
        grade: '--',
        gradePoints: 0.0,
      ),
    ],
    gpaHistory: const [3.60, 3.43],
    attendance: const [
      CourseAttendance(
        courseCode: 'SE621',
        courseName: 'Advanced Software Architecture',
        attended: 19,
        total: 24,
      ),
      CourseAttendance(
        courseCode: 'SE631',
        courseName: 'Software Quality Assurance',
        attended: 20,
        total: 24,
      ),
      CourseAttendance(
        courseCode: 'SE699',
        courseName: 'Thesis-I',
        attended: 10,
        total: 12,
      ),
    ],
    dateOfBirth: '1999-03-02',
    gender: 'Male',
    bloodGroup: 'O+',
    cnic: '42101-7654321-0',
    personalEmail: 'usman.farooq@gmail.com',
    universityEmail: 'ms231112@nu.edu.pk',
    phone: '+92 333 4567890',
    emergencyContact: '+92 300 7788990',
    address: 'Saadi Town, Scheme 33, Karachi',
    research: const ResearchInfo(
      title: 'Efficient Test Case Prioritization for CI/CD Pipelines',
      supervisorName: 'Dr. Sana Ahmed',
      coSupervisor: null,
      researchArea: 'Software Testing and DevOps',
      publicationsCount: 1,
      defenseDate: null,
      defenseStatus: 'In Progress',
      conferencePresentations: 1,
    ),
    feeStatus: FeeStatus.pending,
    outstandingDues: 92000,
    scholarshipName: null,
    scholarshipDiscount: null,
    profileImagePath: null,
  ),
  StudentProfile(
    studentId: 'PHD21-080',
    fullName: 'Dr. Hina Siddiqui',
    department: 'Computer Science',
    faculty: 'Faculty of Computing',
    program: 'PhD Computer Science',
    programType: ProgramType.doctorate,
    currentSemester: 6,
    totalSemesters: 8,
    enrollmentStatus: EnrollmentStatus.active,
    academicStanding: AcademicStanding.goodStanding,
    cgpa: 3.88,
    semesterGpa: 3.90,
    creditHoursCompleted: 36,
    creditHoursRequired: 48,
    currentCourses: const [
      SemesterCourse(
        code: 'PHD801',
        name: 'Doctoral Research Seminar',
        creditHours: 3,
        grade: 'A',
        gradePoints: 4.0,
      ),
      SemesterCourse(
        code: 'PHD899',
        name: 'Dissertation',
        creditHours: 9,
        grade: '--',
        gradePoints: 0.0,
      ),
    ],
    gpaHistory: const [3.75, 3.80, 3.82, 3.86, 3.88, 3.90],
    attendance: const [
      CourseAttendance(
        courseCode: 'PHD801',
        courseName: 'Doctoral Research Seminar',
        attended: 14,
        total: 16,
      ),
      CourseAttendance(
        courseCode: 'PHD899',
        courseName: 'Dissertation Meetings',
        attended: 11,
        total: 12,
      ),
    ],
    dateOfBirth: '1994-11-20',
    gender: 'Female',
    bloodGroup: 'A+',
    cnic: '42501-2468135-9',
    personalEmail: 'hina.siddiqui@gmail.com',
    universityEmail: 'phd21080@nu.edu.pk',
    phone: '+92 311 2233445',
    emergencyContact: '+92 321 1122334',
    address: 'PECHS Block 2, Karachi',
    research: const ResearchInfo(
      title: 'Robust Federated Learning Models for Urdu NLP',
      supervisorName: 'Prof. Dr. Bilal Hashmi',
      coSupervisor: 'Dr. Maria Qureshi',
      researchArea: 'Machine Learning and NLP',
      publicationsCount: 4,
      defenseDate: '2027-01-18',
      defenseStatus: 'Proposal Approved',
      conferencePresentations: 6,
    ),
    feeStatus: FeeStatus.paid,
    outstandingDues: 0,
    scholarshipName: 'HEC Indigenous PhD Fellowship',
    scholarshipDiscount: 100,
    profileImagePath: null,
  ),
];
